start-at-login = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 4
inner.vertical =   4
outer.left =       0
outer.bottom =     0
outer.top =        0
outer.right =      0

[mode.main.binding]
ctrl-alt-h = 'focus left'
ctrl-alt-j = 'focus down'
ctrl-alt-k = 'focus up'
ctrl-alt-l = 'focus right'

ctrl-alt-shift-h = 'move left'
ctrl-alt-shift-j = 'move down'
ctrl-alt-shift-k = 'move up'
ctrl-alt-shift-l = 'move right'

ctrl-alt-up = 'resize smart +50'
ctrl-alt-down = 'resize smart -50'
ctrl-alt-0 = 'balance-sizes'

ctrl-alt-1 = 'workspace 1'
ctrl-alt-d = 'workspace D'

ctrl-alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-alt-shift-d = ['move-node-to-workspace D', 'workspace D']

ctrl-alt-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
f = ['layout floating tiling', 'mode main']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['layout floating']
